### ISSUE TITLE
Add Mercury

### ISSUE THREAD

**Issue by suirad** [Civcraft/CBanManagement#1]
All i have in mind for this, is that it will broadcast to all other servers the ban data of a new ban.
From there the server will track that new ban without pulling it from the db.

That is all that is wanted from this to use mercury correct?

@rourke750 @erocs

**Comment by rourke750** [comment]
Yea perfect.  Great work right now, this is exactly what we wanted thank you.

**Comment by suirad** [comment]
Sounds good, consider it done. Done coding for the night, so i am dumping issues for everything i can remember still needs to be done. Be sure to make one if you can think of anything missing.

**Comment by rourke750** [comment]
Alright thank you.
