### ISSUE TITLE
Temp/Timed bans

### ISSUE THREAD

**Issue by suirad** [Civcraft/CBanManagement#2]
There is already a temp ban flag, is it desired for this to automatically track time info for temp/timed bans and automatically unban, or will the other plugins doing those bans do that? I.E. AFKRPG

@programmerdan @rourke750

**Comment by rourke750** [comment]
@programmerdan going to let you decide.  I think the only real case would be for afkpg which I'm not sure how you would take the direction for it.

**Comment by suirad** [comment]
Well the other use case i had in mind, was normal temporary bans done by @ttk2 that expire after a specific time period. These bans would expire and be removed from the db with no further action; if desired.

**Comment by erocs** [comment]
I don't believe the admins have ever issued a timed ban via MC. Plugins have, but for administrative bans of any form the players have to contact the admins to get them lifted, even if an end date was specified.

Edit: But yes, plugins would find this a necessity.

**Comment by suirad** [comment]
I'll wait to hear back from @programmerdan before i do this.
@ttk2 feel free to chime in too.

**Comment by ProgrammerDan** [comment]
I'm a little light on the background here, but looks like we're re-implementing ban management to be cross-shard aware? 

In that case, absolutely timed bans are necessary. I think AFKPGC will be the only consumer at the moment, but future plugins could benefit. 

In terms of architecture, will you leave it up to the calling plugin to issue the "kick", or will you include that here as well?

**Comment by suirad** [comment]
I will be including the kick. Since the ban message will be set, the kick
itself is a simple addition.

**Comment by ProgrammerDan** [comment]
Perfect, that's great. I'd love to be able to issue a single Ban call and for the plugin to literally stop caring after that point, would be very nice.

Thanks for working on this.

**Comment by suirad** [comment]
Added the auto-kick in [this commit](https://github.com/Civcraft/CBanManagement/commit/116f304dcc2d0e502fa1ceef0440196ac3d06970#diff-c40cb7691f5b4611366f8b96c8a43c2dR83).
Should temp bans really need their own banlevel, or should they just be considered any ban that has an expiry date, and just keep the low/med/high levels?

**Comment by suirad** [comment]
Completed
