### ISSUE TITLE
MySQLSyntaxErrorException SqlManager.updateBan

### ISSUE THREAD

**Issue by erocs** [Civcraft/CBanManagement#26]
> ban XYZ
> [01:18:13 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'expiry' in 'field list'
> [01:18:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [01:18:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> [01:18:13 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [01:18:13 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [01:18:13 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
> [01:18:13 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:387)
> [01:18:13 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
> [01:18:13 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
> [01:18:13 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
> [01:18:13 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
> [01:18:13 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
> [01:18:13 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
> [01:18:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
> [01:18:13 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
> [01:18:13 WARN]:        at vg.civcraft.mc.cbanman.database.SqlManager.updateBan(SqlManager.java:143)
> [01:18:13 WARN]:        at vg.civcraft.mc.cbanman.CBanManagement.banPlayer(CBanManagement.java:148)
> [01:18:13 WARN]:        at vg.civcraft.mc.cbanman.CBanManagement.banPlayer(CBanManagement.java:124)
> [01:18:13 WARN]:        at vg.civcraft.mc.cbanman.handler.CommandHandler.handleBan(CommandHandler.java:143)
> [01:18:13 WARN]:        at vg.civcraft.mc.cbanman.handler.CommandHandler.onCommand(CommandHandler.java:36)
> [01:18:13 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [01:18:13 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
> [01:18:13 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
> [01:18:13 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
> [01:18:13 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438)
> [01:18:13 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401)
> [01:18:13 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
> [01:18:13 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
> [01:18:13 WARN]:        at java.lang.Thread.run(Thread.java:745)
> [01:18:13 INFO]: Banned: XYZ

**Comment by Maxopoly** [comment]
Duplicate, see https://github.com/Civcraft/CBanManagement/issues/25
