### ISSUE TITLE
Add ban by name using namelayer

### ISSUE THREAD

**Issue by suirad** [Civcraft/CBanManagement#3]
This would allow the banman to ban by player name, calling namelayer to grab the uuid.
Also should trap the /ban command to use that.

**Comment by rourke750** [comment]
Perfect, also try make it a soft dependency.  Shouldn't be too difficult.  The reason for a soft dependency is because maybe some servers won't be using namelayer and then those namelayer cases wouldnt apply to them.  Overall so far so good.

**Comment by suirad** [comment]
Already listed in the plugin.yml as a soft depend. One step ahead of ya ;).
