### ISSUE TITLE
Administrative commands

### ISSUE THREAD

**Issue by erocs** [Civcraft/CBanManagement#4]
For banning / unbanning / updating / inspecting bans.

**Comment by suirad** [comment]
Will be completed after #3

**Comment by suirad** [comment]
Added, see below. As requested by @ttk2, the /ban and /unban take a list of player names. /ban gives an administrative ban(banlevel, pluginname, and ban message are set in config). /unban wipes all bans on user.
![picher](https://i.gyazo.com/4435efe198ef4f896f40025d3d93d1db.png)

**Comment by erocs** [comment]
Could we also get a /reloadcache to flush the ban lists and reload from the DB? For inspecting bans I guess we can always head to the DB.

**Comment by suirad** [comment]
Sure i could add that, no problem. I'll do it first thing when i work on it again.

**Comment by suirad** [comment]
I may also tweak checkban to provide the ban message for each ban to the requester.

**Comment by erocs** [comment]
Thanks! It hasn't been often that we've needed to flush a plugin's cache, but having the functionality available has helped in the past.

**Comment by suirad** [comment]
both are complete in latest commit.
![percher](https://i.gyazo.com/15788ed47c0f6d4fa688efdb2d09cb3c.png)
