### ISSUE TITLE
Track plugin which initiated the ban

### ISSUE THREAD

**Issue by erocs** [Civcraft/CBanManagement#5]
There could be multiple simultaneous bans for a player; alt-ban, NoCheat ban, administrative ban. This should track which plugin the ban originated with and disallow other plugins from modifying bans they do not own. Possibly with a configurable white-list of plugins which this doesn't pertain to.

**Comment by rourke750** [comment]
Also store multiple bans for a player.  Example they get alt banned by pp we would want this as a low level ban but then we find out they were hacking and set a high ban level.  So when a player joins they will see the high ban level but lets say they get disassociated that ban being removed wont unban them and vise versa, the ban we removed from them hacking is gone but they are still pp alt banned.

**Comment by suirad** [comment]
Currently it does track a "plugin name" for each ban. The white list could be done easily, as currently each subsequent ban on top of an existing one just updates it.
Actually, would it be better to rely on the ban level for this? 
If ban level of new ban is >= previous ban, apply, if not disregard.

**Comment by suirad** [comment]
Will be addressed in #8
