### ISSUE TITLE
Ban priority levels, enum or int

### ISSUE THREAD

**Issue by erocs** [Civcraft/CBanManagement#6]
Should the ban priority levels be an int so plugins can use a configurable ban priority? Then admins can adjust how different plugin bans interact.

Also, then creating a second ban at the same priority could be rejected, regardless of plugin (not sure if that'd be useful having 2 plugins ban at the same priority and the first winning).

**Comment by rourke750** [comment]
Rather have enums otherwise whats stopping something from issuing a ban level 1000.  Keeps everything sain.  Maybe db store it as an int.

**Comment by erocs** [comment]
Who cares if it issues a ban level 1000? If the plugin was configured to use that ban level, what should stop it if that's what the admins wanted?

**Comment by erocs** [comment]
So right now there's 4 levels of a ban, let's say 0 1 2 3. So administrative bans would be highest, 3. Next up, alt-bans at 2. Probably NoCheat bans at 1. And lastly AFKPGC bans at 0. If any other plugins want to make a ban, where would they fit in the priority levels? If multiple plugins make a ban at level 2, which are all recorded in the DB, which ban message gets displayed? Using ints allows the configurable levels so admins can re-order priorities and disambiguate priorities between plugins.

**Comment by rourke750** [comment]
Because then how could a plugin ever ensure it has the highest ban.  We want to make sure everything will always work together plugin wise.  All plugins should never really have higher duristiction over /ban or any manual bans and as such we need to make sure admins don't have to jump hoops to override a plugin.

**Comment by suirad** [comment]
Going to keep the ban level enums, while utilizing multi bans in #8.
Closing.
