### ISSUE TITLE
Multiple bans

### ISSUE THREAD

**Issue by suirad** [Civcraft/CBanManagement#8]
Right now, i have it preventing duplicate and overwriting previous bans with new ones. Both internally and in the DB. Should i have it store bans for duplicate uuids? That way if one is removed the other(s) stay in effect? 
@rourke750 @erocs

**Comment by erocs** [comment]
The private key would be (UUID, PluginName), so yes, bans from other plugins would stay in effect.

**Comment by suirad** [comment]
I am going to make it store one ban per plugin name. Any addition bans by the same plugin will overwrite the previous. 

Should i make it ignore new bans, with the same plugin name, but of lower ban level?

**Comment by erocs** [comment]
Sounds fine to me.
